plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {}

loom {
	splitEnvironmentSourceSets()
	mods {
		"askgemini" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

processResources {
	inputs.property "version", project.version
	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	options.release = 21
	options.encoding = "UTF-8"
}

java {
	withSourcesJar()
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

jar {
	def arcName = project.base.archivesName.get()
	def modVersion = project.version
	def modName = project.name

	inputs.property("archivesName", arcName)

	from("LICENSE") {
		rename { fileName -> "${fileName}_${arcName}" }
	}

	manifest {
		attributes([
				"Specification-Title"     : "AskGemini",
				"Specification-Vendor"    : "Luks_X_A",
				"Specification-Version"   : modVersion,
				"Implementation-Title"    : modName,
				"Implementation-Version"  : modVersion,
				"Implementation-Vendor"   : "Luks_X_A"
		])
	}
}

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}

// Copy external mods to the run/mods directory before running the client in the development environment
tasks.register('copyExternalMods', Copy) {
	def externalModsDir = layout.projectDirectory.dir("external-mods")

	from(externalModsDir)
	include("**/*.jar")
	into(layout.projectDirectory.dir("run/mods"))

	onlyIf {
		externalModsDir.asFile.exists() && externalModsDir.asFile.listFiles()?.any { it.name.endsWith('.jar') }
	}
}

// Guarantee that external mods are copied before running the client
tasks.named('runClient').configure {
	dependsOn(copyExternalMods)
}
